apiVersion: apps/v1
kind: Deployment
metadata:
  name: catapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catapp
  template:
    metadata:
      labels:
        app: catapp
    spec:
      containers:
        - name: catapp
          image: 671394177905.dkr.ecr.ap-south-1.amazonaws.com/catapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: catapp
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: catapp